2025-07-21 23:05:51,593 - database - INFO - Database initialized successfully
2025-07-21 23:05:51,601 - bot - INFO - Starting FrienGO bot...
2025-07-21 23:05:51,602 - scheduler - INFO - Ping scheduler started
2025-07-21 23:05:54,943 - bot - INFO - FrienGO bot started successfully!
2025-07-21 23:07:15,541 - voting - INFO - Created voting 1 in chat -1002797546947
2025-07-21 23:07:25,352 - voting - INFO - User 5259577325 voted for option 4 in voting 1
2025-07-21 23:07:30,171 - voting - INFO - User 5259577325 voted for option 2 in voting 1
2025-07-21 23:07:33,214 - voting - INFO - User 5259577325 removed vote for option 2 in voting 1
2025-07-21 23:07:34,631 - voting - INFO - User 5259577325 voted for option 2 in voting 1
2025-07-21 23:09:07,868 - voting - INFO - User 476658130 voted for option 1 in voting 1
2025-07-21 23:09:11,296 - voting - INFO - User 476658130 voted for option 4 in voting 1
2025-07-21 23:09:13,772 - voting - INFO - User 476658130 voted for option 6 in voting 1
2025-07-21 23:09:47,895 - voting - INFO - User 476658130 removed vote for option 4 in voting 1
2025-07-21 23:09:48,440 - voting - INFO - User 476658130 removed vote for option 1 in voting 1
2025-07-21 23:09:49,148 - voting - INFO - User 476658130 removed vote for option 6 in voting 1
2025-07-21 23:17:41,284 - voting - INFO - User 5259577325 voted for option 5 in voting 1
2025-07-21 23:28:13,930 - __main__ - INFO - Получен сигнал завершения, останавливаем бота...
2025-07-21 23:28:14,552 - bot - INFO - Stopping FrienGO bot...
2025-07-21 23:28:14,553 - scheduler - INFO - Ping scheduler stopped
2025-07-21 23:28:14,792 - bot - INFO - FrienGO bot stopped
2025-07-21 23:28:22,836 - __main__ - INFO - Получен сигнал завершения, останавливаем бота...
2025-07-21 23:28:23,563 - bot - INFO - Stopping FrienGO bot...
2025-07-21 23:28:23,564 - scheduler - INFO - Ping scheduler stopped
2025-07-21 23:28:23,565 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-21' coro=<FrienGoBot.stop_bot() done, defined at /Users/n.novichkov/PycharmProjects/FrienGO/bot.py:320> exception=RuntimeError('This Updater is not running!')>
Traceback (most recent call last):
  File "/Users/n.novichkov/PycharmProjects/FrienGO/bot.py", line 325, in stop_bot
    await query.answer(message, show_alert=True)
  File "/Users/n.novichkov/PycharmProjects/FrienGO/.venv/lib/python3.9/site-packages/telegram/ext/_updater.py", line 805, in stop
    raise RuntimeError("This Updater is not running!")
RuntimeError: This Updater is not running!
2025-07-21 23:28:27,670 - __main__ - INFO - Получен сигнал завершения, останавливаем бота...
2025-07-21 23:28:28,582 - bot - INFO - Stopping FrienGO bot...
2025-07-21 23:28:28,583 - scheduler - INFO - Ping scheduler stopped
2025-07-21 23:28:28,583 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-22' coro=<FrienGoBot.stop_bot() done, defined at /Users/n.novichkov/PycharmProjects/FrienGO/bot.py:320> exception=RuntimeError('This Updater is not running!')>
Traceback (most recent call last):
  File "/Users/n.novichkov/PycharmProjects/FrienGO/bot.py", line 325, in stop_bot
    await query.answer(message, show_alert=True)
  File "/Users/n.novichkov/PycharmProjects/FrienGO/.venv/lib/python3.9/site-packages/telegram/ext/_updater.py", line 805, in stop
    raise RuntimeError("This Updater is not running!")
RuntimeError: This Updater is not running!
2025-07-21 23:28:29,416 - __main__ - INFO - Получен сигнал завершения, останавливаем бота...
2025-07-21 23:28:29,585 - bot - INFO - Stopping FrienGO bot...
2025-07-21 23:28:29,586 - scheduler - INFO - Ping scheduler stopped
2025-07-21 23:28:29,586 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23' coro=<FrienGoBot.stop_bot() done, defined at /Users/n.novichkov/PycharmProjects/FrienGO/bot.py:320> exception=RuntimeError('This Updater is not running!')>
Traceback (most recent call last):
  File "/Users/n.novichkov/PycharmProjects/FrienGO/bot.py", line 325, in stop_bot
    await query.answer(message, show_alert=True)
  File "/Users/n.novichkov/PycharmProjects/FrienGO/.venv/lib/python3.9/site-packages/telegram/ext/_updater.py", line 805, in stop
    raise RuntimeError("This Updater is not running!")
RuntimeError: This Updater is not running!
2025-07-21 23:28:29,605 - __main__ - INFO - Получен сигнал завершения, останавливаем бота...
2025-07-21 23:28:30,589 - bot - INFO - Stopping FrienGO bot...
2025-07-21 23:28:30,589 - scheduler - INFO - Ping scheduler stopped
2025-07-21 23:28:30,589 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-24' coro=<FrienGoBot.stop_bot() done, defined at /Users/n.novichkov/PycharmProjects/FrienGO/bot.py:320> exception=RuntimeError('This Updater is not running!')>
Traceback (most recent call last):
  File "/Users/n.novichkov/PycharmProjects/FrienGO/bot.py", line 325, in stop_bot
    await query.answer(message, show_alert=True)
  File "/Users/n.novichkov/PycharmProjects/FrienGO/.venv/lib/python3.9/site-packages/telegram/ext/_updater.py", line 805, in stop
    raise RuntimeError("This Updater is not running!")
RuntimeError: This Updater is not running!
2025-07-21 23:29:37,743 - database - INFO - Database initialized successfully
2025-07-21 23:29:37,750 - bot - INFO - Starting FrienGO bot...
2025-07-21 23:29:37,751 - scheduler - INFO - Ping scheduler started
2025-07-21 23:29:38,032 - bot - INFO - FrienGO bot started successfully!
2025-07-21 23:30:24,314 - voting - INFO - Created voting 2 in chat -1002797546947
2025-07-21 23:30:38,562 - voting - INFO - User 476658130 voted for option 15 in voting 2
2025-07-21 23:30:42,125 - voting - INFO - User 5259577325 voted for option 10 in voting 2
2025-07-21 23:30:46,713 - voting - INFO - User 5259577325 voted for option 9 in voting 2
2025-07-21 23:31:17,078 - voting - INFO - Created voting 3 in chat -1002797546947
2025-07-26 10:51:26,269 - database - INFO - Database initialized successfully
2025-07-26 10:51:26,278 - bot - INFO - Starting FrienGO bot...
2025-07-26 10:51:26,278 - scheduler - INFO - Ping scheduler started
2025-07-26 10:51:26,544 - bot - INFO - FrienGO bot started successfully!
2025-07-26 10:51:26,608 - scheduler - INFO - Sent 24h ping for voting 1
2025-07-26 10:51:26,848 - scheduler - INFO - Sent 48h ping for voting 1
2025-07-26 10:51:27,059 - scheduler - INFO - Sent 72h ping for voting 1
2025-07-26 10:51:27,195 - scheduler - INFO - Sent 24h ping for voting 2
2025-07-26 10:51:27,285 - scheduler - INFO - Sent 48h ping for voting 2
2025-07-26 10:51:32,295 - bot - ERROR - Error sending ping message: Timed out
2025-07-26 10:51:32,303 - scheduler - INFO - Sent 72h ping for voting 2
2025-07-26 10:51:34,446 - scheduler - INFO - Sent 24h ping for voting 3
2025-07-26 10:51:34,557 - scheduler - INFO - Sent 48h ping for voting 3
2025-07-26 10:51:34,645 - scheduler - INFO - Sent 72h ping for voting 3
2025-07-26 10:55:42,165 - voting - INFO - User 5259577325 voted for option 21 in voting 3
2025-07-26 10:55:53,880 - voting - INFO - User 5259577325 voted for option 19 in voting 3
2025-07-26 10:55:55,743 - voting - INFO - User 5259577325 removed vote for option 19 in voting 3
2025-07-26 10:56:27,354 - __main__ - INFO - Получен сигнал завершения, останавливаем бота...
2025-07-26 10:56:27,900 - bot - INFO - Stopping FrienGO bot...
2025-07-26 10:56:27,901 - scheduler - INFO - Ping scheduler stopped
2025-07-26 10:56:31,133 - bot - INFO - FrienGO bot stopped
2025-07-26 10:56:38,619 - __main__ - INFO - Получен сигнал завершения, останавливаем бота...
2025-07-26 10:56:38,912 - bot - INFO - Stopping FrienGO bot...
2025-07-26 10:56:38,913 - scheduler - INFO - Ping scheduler stopped
2025-07-26 10:56:38,913 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-19' coro=<FrienGoBot.stop_bot() done, defined at /Users/n.novichkov/PycharmProjects/FrienGO/bot.py:426> exception=RuntimeError('This Updater is not running!')>
Traceback (most recent call last):
  File "/Users/n.novichkov/PycharmProjects/FrienGO/bot.py", line 431, in stop_bot
    """Остановить бота"""
  File "/Users/n.novichkov/PycharmProjects/FrienGO/.venv/lib/python3.9/site-packages/telegram/ext/_updater.py", line 805, in stop
    raise RuntimeError("This Updater is not running!")
RuntimeError: This Updater is not running!
2025-07-26 10:56:46,582 - database - INFO - Database initialized successfully
2025-07-26 10:56:46,590 - bot - INFO - Starting FrienGO bot...
2025-07-26 10:56:46,590 - scheduler - INFO - Ping scheduler started
2025-07-26 10:56:46,853 - bot - INFO - FrienGO bot started successfully!
2025-07-26 10:57:11,075 - voting - INFO - Created voting 4 in chat -1002797546947
2025-07-26 10:57:12,925 - voting - INFO - User 5259577325 voted for option 25 in voting 4
2025-07-26 11:01:36,745 - database - INFO - Database initialized successfully
2025-07-26 11:01:36,752 - bot - INFO - Starting FrienGO bot...
2025-07-26 11:01:36,752 - scheduler - INFO - Ping scheduler started
2025-07-26 11:01:37,031 - bot - INFO - FrienGO bot started successfully!
2025-07-26 11:02:02,485 - bot - INFO - Unpinned voting message 75 in chat -1002797546947
2025-07-26 11:02:04,509 - bot - INFO - Unpinned previous voting message 75 in chat -1002797546947
2025-07-26 11:02:04,514 - voting - INFO - Created voting 5 in chat -1002797546947
2025-07-26 11:02:04,719 - bot - INFO - Pinned voting message 83 in chat -1002797546947
